steps:
  - label: ":rocket: Upload All Pipeline Chunks"
    key: "upload-chunks"
    command: |
      echo "🚀 Starting upload of all pipeline chunks..."
      echo "This will upload 40 separate pipelines, each with 500 jobs"
      echo "Total jobs across all chunks: 20,000"
      echo ""
      
      # Make sure the script is executable
      chmod +x .buildkite/upload-all-chunks.sh
      
      # Run the upload script
      ./.buildkite/upload-all-chunks.sh
      
      echo ""
      echo "✅ All pipeline chunks have been uploaded!"
      echo "Check the Buildkite dashboard to see all 40 pipelines running"
    agents:
      queue: "test-agent"
    
  - wait: ~
    continue_on_failure: true
    
  - label: ":information_source: Pipeline Upload Summary"
    key: "summary"
    command: |
      echo "📊 Pipeline Upload Summary"
      echo "========================="
      echo "✅ Uploaded: 40 pipeline chunks"
      echo "📈 Jobs per chunk: 500"
      echo "🎯 Total jobs: 20,000"
      echo ""
      echo "📁 Chunk files location: .buildkite/chunks/"
      echo "📖 Documentation: .buildkite/chunks/README.md"
      echo ""
      echo "💡 Individual chunk upload example:"
      echo "   buildkite-agent pipeline upload .buildkite/chunks/pipeline-echo-chunk-01.yml"
      echo ""
      echo "🔍 Monitor all pipelines in your Buildkite dashboard"
    agents:
      queue: "test-agent"
