steps:
  - label: "Test Vault plugin"
    key: "test-step"
    agents:
      queue: "angwang-test-queue"
    command: |
      echo "=== Debug DUMMY variable ==="
      echo "DUMMY from Vault: '\$$DUMMY'"
      env | grep DUMMY || echo "No DUMMY variables found in environment"
    plugins:
      - .buildkite/plugins/vault-secrets:
          secrets:
            - path: "secret/jenkins/rt-tests/angwang-dummy-test-secret"
              env_name: "DUMMY"
  # - label: "Run Bazel tests and upload test results with redaction"
  #   key: "test-step"
  #   agents:
  #     queue: "angwang-test-queue"
  #   env:
  #     # this is example-test-suite
  #     BUILDKITE_ANALYTICS_TOKEN: "DbCqb15hQkNeyu2j2i92y2Gx"
  #   command: |
  #     bazel test //tests/...
  #   plugins:
  #     - .buildkite/plugins/test-engine-uploader:
  #         file_pattern: "bazel-testlogs/**/*.xml"
  #         redact: true
